---
# Name of your site (displayed in the header)
title: SiBBr - MZUSP - Entomologia
theme: jekyll-theme-cayman
---



# Short bio or description (displayed in the header)
description: Conteúdo referente ao projeto de digitalização das coleções entomológicas do MZUSP integrado ao SiBBr
