---
theme: jekyll-theme-cayman
---

# Name of your site (displayed in the header)
name: SiBBr - MZUSP - Entomologia

# Short bio or description (displayed in the header)
description: Conteúdo referente ao projeto de digitalização das coleções entomológicas do MZUSP integrado ao SiBBr
